VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IItem"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public Function getRqm() As Long

End Function

Public Sub setRqm(v As Long)

End Sub

Public Sub addRqm(v As Long)

End Sub

Public Function getInTransits() As Collection

End Function

Public Function getEBAL() As Range

End Function

Public Sub setEBAL(r As Range)

End Sub

Public Function getTransitItem() As ITransit

End Function

Public Sub addTtransit(pus As ITransit)

End Sub

Public Function getDate() As Date

End Function

Public Sub setDate(d As Date)

End Sub

Public Function getSumOfQty() As Long

End Function



